A11 y 16 local storage
A11y-Game/A11y-Game pull request #21
Opened 2024-05-14 13:08 UTC by Pycxtv

## Todo ✅
- [X] Pull-Request-Titel inkludiert die User-Story-Nummer
- [X] Akzeptanzkriterien der User Story erfüllt
- [ ] Unit Tests sind erfolgreich
- [ ] Unit Tests für die neue Funktionalität geschrieben
- [X] Design erledigt
  - [ ] WCAG Level A erfüllt
  - [X] Light- und Darkmode unterstützt
- [X] US vom PO abgenommen inkl. Design
- [X] Screenshots der neuen Funktionalität hier hinzugefügt

> [!TIP]
> Nach dem Review in `main` **mergen** & User Story **in Jira aktualisieren** 💡

## Screenshots 📷
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/0984acc8-6104-4da5-86b7-173facd1448d)
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/db3d2cab-4eae-405a-ae63-81d1c94ec765)

2024-05-14 20:47 UTC, felixwollmann requested changes
Hier ein paar Kommentare für dich :)

2024-05-14 20:47 UTC, felixwollmann commented on components/Level.vue
> +        const progressStore = useProgressStore();
warum `use..` hier wenn wir vorher `mapStores` verwenden?

2024-05-14 20:47 UTC, felixwollmann commented on composables/themeChanger.js
> +
Please autoformat

2024-05-14 20:47 UTC, felixwollmann commented on composables/themeChanger.js
> +    initialize = true;
1. es sollte wohl `initialized` auf true gesetzt werden und nicht `initialize`
2. wozu gibt es die Variable `initialized` überhaupt, sie wird nirgendwo benutzt

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
formatieren bitte.

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +					</picture>
Ich hätte gedacht wir verwenden nur mehr `img`s mit SVGs

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +		<header class="flex justify-between w-11/12 h-20 mt-6 mx-auto mb-6 items-center">
mt & mb => my

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +				<button type="button" class="ml-auto mr-16" @click="toggleTheme()">
bitte einheitlich entweder Methoden aufrufen mit () oder das () weglassen

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +					</div>
das `dark:hidden` bzw. `dark:block` kann man auf dem Icon selbst machen, da muss man nicht das div rundherum verstecken

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +				<button type="button" class="ml-auto mr-16" @click="toggleTheme()">
margin in einer flexbox?

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +				<NuxtLink to="/#about" :external=true class="font-heading dark:text-text-dark text-text-light underline text-2xl">
```suggestion
				<NuxtLink to="/#about" :external="true" class="font-heading dark:text-text-dark text-text-light underline text-2xl">
```

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +					}}</span>
Den ganzen Text in einer Zeile wär zum Codelesen einfacher, aber vielleicht formatiert das die Autoformatierung anders, idk
```suggestion
					<span class="text-2xl dark:text-text-dark text-text-light">
					        Level {{ progressStore.currentLevel }} of {{ progressStore.levelCount }}
					</span>
```

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +					us</NuxtLink>
About us darf in der gleichen Zeile stehen

2024-05-14 20:47 UTC, felixwollmann commented on layouts/default.vue
> +		</footer>
Ich glaub nicht, dass wir das wollen, oder?
Also wer will den andauernd den Progress zurücksetzen? Vor allem, weil der Platz am Bildschirm eh schon so wenig ist dank unserem ganzen Padding und so

2024-05-14 20:47 UTC, felixwollmann commented on pages/index.vue
>      <div class="flex place-content-between items-center">
Wozu `place-content-between`? Da nix grid

2024-05-14 20:47 UTC, felixwollmann commented on pages/index.vue
>        <button type="button" class="ml-auto mr-8" @click="toggleTheme()">
margin in flex igitt

2024-05-14 20:47 UTC, felixwollmann commented on stores/ProgressStore.js
> +    // Does nothing as long as the level is inaccessable
Wenn du schon Kommentare schreibst, dann warum nicht als JSDoc :) (ebenso ein paar Zeilen darunter)
```suggestion
    /** Does nothing as long as the level is inaccessable */
```

2024-05-14 20:50 UTC, Pycxtv commented on pages/index.vue
>      <div class="flex place-content-between items-center">
Hab nicht ich geschrieben, muss wohl vom merge von der Welcome Page kommen...

2024-05-15 18:56 UTC, Pycxtv commented on composables/themeChanger.js
> +    initialize = true;
Ihr Wert wird von themeInitialized returned und in default.vue und index.vue wird nur initialisiert, wenn der Wert false ist

2024-05-17 13:32 UTC, Pycxtv commented on layouts/default.vue
> +					</div>
Das funktioniert tatsächlich nicht, habe es damals ausprobiert und nur deshalb das div erstellt

2024-05-17 15:52 UTC, felixwollmann requested changes

2024-05-17 15:52 UTC, felixwollmann commented on components/Level.vue
> +        // const progressStore = useProgressStore();
Den Kommentar bitte weg :)

2024-05-17 15:52 UTC, felixwollmann commented on stores/ProgressStore.js
> +      /** Necessary for SSR */
Das ist kein JSDoc-Kommentar, der muss so wie JavaDoc etwas kommentieren
```suggestion
      // Necessary for SSR
```

2024-05-17 15:53 UTC, felixwollmann approved these changes

2024-05-17 21:57 UTC, Pycxtv commented on components/Level.vue
> +        // const progressStore = useProgressStore();
```suggestion
        
```

2024-05-17 22:05 UTC, merged