A11 y 74 benachrichtigung bei letztem level
A11y-Game/A11y-Game pull request #25
Opened 2024-05-22 20:15 UTC by Pycxtv

## Todo ✅
- [X] Pull-Request-Titel inkludiert die User-Story-Nummer
- [X] Akzeptanzkriterien der User Story erfüllt
- [ ] Unit Tests sind erfolgreich
- [ ] Unit Tests für die neue Funktionalität geschrieben
- [X] Design erledigt
  - [ ] WCAG Level A erfüllt
  - [ ] Light- und Darkmode unterstützt
- [X] US vom PO abgenommen inkl. Design
- [X] Screenshots der neuen Funktionalität hier hinzugefügt

> [!TIP]
> Nach dem Review in `main` **mergen** & User Story **in Jira aktualisieren** 💡

## Screenshots 📷
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/33ac2743-52fc-4097-8a33-61d7b253ec5d)
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/0e8686b3-8444-4ca6-8e48-8c38ccea0e2c)

2024-05-23 08:43 UTC, EinSev approved these changes

2024-05-23 12:08 UTC, felixwollmann requested changes

2024-05-23 12:08 UTC, felixwollmann commented on components/Level.vue
> +      var defaults = {
`const` oder `let` falls veränderung, nie `var`

2024-05-23 12:08 UTC, felixwollmann commented on components/Level.vue
> +          ...defaults,
woher kommt `defaults`

2024-05-23 12:08 UTC, felixwollmann commented on components/Level.vue
> +        alert(
https://vuejs.org/api/general#nexttick

2024-05-23 12:08 UTC, felixwollmann commented on components/Level.vue
> +              : 'Going to next level disallowed: Solve the task first'
`isCorrect ? (isLastLevel ? 'a' : 'b') : c` wäre lesbarer

2024-05-23 12:08 UTC, felixwollmann commented on components/Level.vue
> +            isLastLevel && isCorrect
wär's nicht schön, wenn man beim letzten level immer schon das party-emoji sieht? weil sonst ist es verwirrend, zuerst ein Pfeil nach rechts und dann plötzlich so ein emoji

2024-05-23 12:08 UTC, felixwollmann commented on components/Level.vue
> +      function fire(particleRatio, opts) {
```suggestion
      function fire(particleRatio: number, opts: ...) {
```

2024-05-23 12:08 UTC, felixwollmann commented on components/Level.vue
> -<script lang="ts">
lass es doch typescript sein

2024-05-25 09:12 UTC, Pycxtv commented on components/Level.vue
> +          ...defaults,
das steht legit 3 Zeilen darüber

2024-05-25 09:50 UTC, felixwollmann approved these changes

2024-05-25 09:58 UTC, merged