A11Y-75-Level-Kontrast-fuer-Text
A11y-Game/A11y-Game pull request #28
Opened 2024-06-02 15:37 UTC by Pycxtv

## Todo ✅
- [X] Pull-Request-Titel inkludiert die User-Story-Nummer
- [X] Akzeptanzkriterien der User Story erfüllt
- [ ] Unit Tests sind erfolgreich
- [ ] Unit Tests für die neue Funktionalität geschrieben
- [X] Design erledigt
  - [ ] WCAG Level A erfüllt
  - [X] Light- und Darkmode unterstützt
- [X] US vom PO abgenommen inkl. Design
- [X] Screenshots der neuen Funktionalität hier hinzugefügt

> [!TIP]
> Nach dem Review in `main` **mergen** & User Story **in Jira aktualisieren** 💡

## Screenshots 📷
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/82a16886-0c68-481b-bc50-f45e8c71d72c)
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/d4749f83-4e70-4d46-b096-64ddd4f3ea53)

2024-06-02 18:36 UTC, felixwollmann requested changes
Bitte autoformatier doch.... :)

2024-06-02 18:36 UTC, felixwollmann commented on pages/levels/4.vue
Non Breaking space wäre schön für diese ganzen Verhältnisse, sonst haben wir was wie folgt:
![image](https://github.com/A11y-Game/A11y-Game/assets/50966625/ba89f994-e358-4be6-bff5-87ead6e91ae4)

2024-06-02 18:36 UTC, felixwollmann commented on components/ColorPickerContrastDisplay.vue
autoformatieren bitte :)

2024-06-02 18:36 UTC, felixwollmann commented on components/ColorPickerContrastDisplay.vue
> +    contrastRestriction: {
Das könnte auch eine Zahl sein, also type number

2024-06-02 18:36 UTC, felixwollmann commented on components/ColorPickerContrastDisplay.vue
> +        Contrast ratio: <b>{{ contrast.ratioOneTo }} : 1</b>
```suggestion
        Contrast ratio: <strong>{{ contrast.ratioOneTo }} : 1</strong>
```

2024-06-02 18:36 UTC, felixwollmann commented on components/ColorPickerContrastDisplay.vue
> +    getContrast(hex1 = "#000000", hex2 = "#FFFFFF") {
die default-werte hier dürfen weg, weil wir wollen die methode ja nie mit diesen aufrufen, oder?
```suggestion
    getContrast(hex1: string, hex2: string) {
```

2024-06-02 18:36 UTC, felixwollmann commented on components/ColorPickerContrastDisplay.vue
> +      let color2rgb = hexToRgb(hex2);
prefer const
```suggestion
      const color1rgb = hexToRgb(hex1);
      const color2rgb = hexToRgb(hex2);
```

2024-06-02 18:36 UTC, felixwollmann commented on pages/levels/4.vue
> +    " contrastRestriction="4.5" />
Du baust v-model nach damit, aber kannst es auch so lassen, wenn du keinen bock drauf hast

2024-06-02 18:36 UTC, felixwollmann commented on pages/levels/4.vue
> +            </button>
Die könnte man jeweils auslagern, weil jetzt haben wir sie schon im Code Editor und hier, aber gleiches wie beim Kommentar davor gilt, das Projekt ist schließlich gleich vorbei

2024-06-02 18:42 UTC, Pycxtv commented on components/ColorPickerContrastDisplay.vue
> +    getContrast(hex1 = "#000000", hex2 = "#FFFFFF") {
Nein, aber beim Loaden wirft er sonst Fehler

2024-06-03 08:03 UTC, felixwollmann approved these changes

2024-06-03 08:47 UTC, merged