A11Y-3-Vor-und-Zurueckbutton
A11y-Game/A11y-Game pull request #6
Opened 2024-04-21 19:18 UTC by Pycxtv

## Todo ✅
- [X] Pull-Request-Titel inkludiert die User-Story-Nummer
- [X] Akzeptanzkriterien der User Story erfüllt
- [ ] Unit Tests sind erfolgreich
- [ ] Unit Tests für die neue Funktionalität geschrieben
- [ ] Design erledigt
  - [ ] WCAG Level A erfüllt
  - [X] Light- und Darkmode unterstützt
- [X] US vom PO abgenommen inkl. Design
- [X] Screenshots der neuen Funktionalität hier hinzugefügt

> [!TIP]
> Nach dem Review in `main` **mergen** & User Story **in Jira aktualisieren** 💡

## Screenshots 📷
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/094bb6ab-3171-4fa2-a3ed-317679a1ed57)
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/8f08e7a3-09fa-4e6e-9647-f2622ae7dc85)
![image](https://github.com/A11y-Game/A11y-Game/assets/75068841/452ce7be-5b45-4f3a-9f79-cd2140979401)

2024-04-21 20:11 UTC, felixwollmann requested changes

2024-04-21 20:11 UTC, felixwollmann commented on app.vue
> +			levelNumber: this.levelNumber = useRoute().fullPath.split('/')[2],
Das ist nicht reactive => wenn man zuerst auf der Hauptseite ist, und dann auf den Link zu Level 1 klickt, steht noch immer "Level of 2" da.

2024-04-21 20:11 UTC, felixwollmann commented on app.vue
> +					document.querySelectorAll('NuxtLink').forEach((el) => el.classList.add('dark'));
Dubios und unsauber, aber ich nehm an irgendwas funktioniert nicht ohne dem, richtig?

2024-04-21 20:11 UTC, felixwollmann commented on app.vue
> +					class="h-11 hidden dark:block">
Genau dazu gibt's ein `picture`-Element

2024-04-21 20:11 UTC, felixwollmann commented on app.vue
> +					<NuxtLink :to="`${parseInt(levelNumber) + 1}`" @click="levelNumber++" class="ml-2">
Bitte statt `mr-2` und `ml-2` flex-gap

2024-04-21 20:11 UTC, felixwollmann commented on app.vue
> +					<NuxtLink :to="`${parseInt(levelNumber) + 1}`" @click="levelNumber++" class="ml-2">
Bitte das `:to=...` in eine computed property und das `@click` in eine Funktion, wäre sauberer

2024-04-21 20:11 UTC, felixwollmann commented on app.vue
> +					<div class=" hidden dark:block">
da ist ein space zu viel, pls autoformatieren durch Alt + Shift + F oder `npm run prettier`

2024-04-21 20:11 UTC, felixwollmann commented on pages/levels/1.vue
> +          <Icon name="ic:round-navigate-next" class="size-12 mx-auto" />
`mx-auto`? Zentrieren doch eher mit flexbox, oder?

2024-04-21 21:02 UTC, Pycxtv commented on app.vue
> +					document.querySelectorAll('NuxtLink').forEach((el) => el.classList.add('dark'));
Nein, geht auch so.

2024-04-22 07:10 UTC, felixwollmann approved these changes
Super, kannst mergen :)

2024-04-22 07:13 UTC, merged